// Code generated by tools/pod-status-codegen from proto/pod/v1/pod_status.proto. DO NOT EDIT.

package agentpod

const (
	StatusQueued       = "queued"
	StatusInitializing = "initializing"
	StatusRunning      = "running"
	StatusPaused       = "paused"
	StatusDisconnected = "disconnected"
	StatusCompleted    = "completed"
	StatusTerminated   = "terminated"
	StatusOrphaned     = "orphaned"
	StatusError        = "error"
)

func AllStatuses() []string {
	return []string{StatusQueued, StatusInitializing, StatusRunning, StatusPaused, StatusDisconnected, StatusCompleted, StatusTerminated, StatusOrphaned, StatusError}
}

func ActiveStatuses() []string {
	return []string{StatusQueued, StatusInitializing, StatusRunning, StatusPaused, StatusDisconnected}
}

func IsPodStatusActive(status string) bool {
	switch status {
	case StatusQueued, StatusInitializing, StatusRunning, StatusPaused, StatusDisconnected:
		return true
	}
	return false
}

func TerminalStatuses() []string {
	return []string{StatusTerminated, StatusOrphaned, StatusError}
}

func IsPodStatusTerminal(status string) bool {
	switch status {
	case StatusTerminated, StatusOrphaned, StatusError:
		return true
	}
	return false
}

func FinishedStatuses() []string {
	return []string{StatusCompleted, StatusTerminated, StatusOrphaned, StatusError}
}

func IsPodStatusFinished(status string) bool {
	switch status {
	case StatusCompleted, StatusTerminated, StatusOrphaned, StatusError:
		return true
	}
	return false
}

func RelayConnectableStatuses() []string {
	return []string{StatusRunning, StatusPaused, StatusDisconnected}
}

func IsPodStatusRelayConnectable(status string) bool {
	switch status {
	case StatusRunning, StatusPaused, StatusDisconnected:
		return true
	}
	return false
}

func ResumableSourceStatuses() []string {
	return []string{StatusCompleted, StatusTerminated, StatusOrphaned}
}

func IsPodStatusResumableSource(status string) bool {
	switch status {
	case StatusCompleted, StatusTerminated, StatusOrphaned:
		return true
	}
	return false
}
