//! Code generated by tools/pod-status-codegen from proto/pod/v1/pod_status.proto. DO NOT EDIT.

pub const QUEUED: &str = "queued";
pub const INITIALIZING: &str = "initializing";
pub const RUNNING: &str = "running";
pub const PAUSED: &str = "paused";
pub const DISCONNECTED: &str = "disconnected";
pub const COMPLETED: &str = "completed";
pub const TERMINATED: &str = "terminated";
pub const ORPHANED: &str = "orphaned";
pub const ERROR: &str = "error";

pub const ALL: [&str; 9] = [QUEUED, INITIALIZING, RUNNING, PAUSED, DISCONNECTED, COMPLETED, TERMINATED, ORPHANED, ERROR];

pub const ACTIVE: [&str; 5] = [QUEUED, INITIALIZING, RUNNING, PAUSED, DISCONNECTED];

pub fn is_active(status: &str) -> bool {
    matches!(status, QUEUED | INITIALIZING | RUNNING | PAUSED | DISCONNECTED)
}

pub const TERMINAL: [&str; 3] = [TERMINATED, ORPHANED, ERROR];

pub fn is_terminal(status: &str) -> bool {
    matches!(status, TERMINATED | ORPHANED | ERROR)
}

pub const FINISHED: [&str; 4] = [COMPLETED, TERMINATED, ORPHANED, ERROR];

pub fn is_finished(status: &str) -> bool {
    matches!(status, COMPLETED | TERMINATED | ORPHANED | ERROR)
}

pub const RELAY_CONNECTABLE: [&str; 3] = [RUNNING, PAUSED, DISCONNECTED];

pub fn is_relay_connectable(status: &str) -> bool {
    matches!(status, RUNNING | PAUSED | DISCONNECTED)
}

pub const RESUMABLE_SOURCE: [&str; 3] = [COMPLETED, TERMINATED, ORPHANED];

pub fn is_resumable_source(status: &str) -> bool {
    matches!(status, COMPLETED | TERMINATED | ORPHANED)
}
