package main

import (
	"errors"
	"fmt"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	codegenv1 "github.com/l8ai-cn/agentcloud/proto/gen/go/codegen/v1"
	podv1 "github.com/l8ai-cn/agentcloud/proto/gen/go/pod/v1"
)

const wirePrefix = "POD_STATUS_"

type status struct {
	wire   string
	groups *codegenv1.PodStatusGroups
}

// goConst / rustConst mirror the naming already used by hand-written code in
// each runtime, so generating these files touches no call sites.
func (s status) goConst() string   { return "Status" + camel(s.wire) }
func (s status) rustConst() string { return strings.ToUpper(s.wire) }

func loadStatuses() ([]status, error) {
	enum := podv1.File_pod_v1_pod_status_proto.Enums().ByName("PodStatus")
	if enum == nil {
		return nil, errors.New("proto.pod.v1.PodStatus not found — run scripts/proto-gen-go.sh")
	}

	var out []status
	values := enum.Values()
	for i := 0; i < values.Len(); i++ {
		value := values.Get(i)
		name := string(value.Name())
		if value.Number() == 0 {
			continue // UNSPECIFIED is a proto3 requirement, never a wire value
		}
		if !strings.HasPrefix(name, wirePrefix) {
			return nil, fmt.Errorf("enum value %s must start with %s", name, wirePrefix)
		}
		groups, err := groupsOf(value)
		if err != nil {
			return nil, err
		}
		out = append(out, status{
			wire:   strings.ToLower(strings.TrimPrefix(name, wirePrefix)),
			groups: groups,
		})
	}
	if len(out) == 0 {
		return nil, errors.New("PodStatus declares no statuses")
	}
	return out, nil
}

func groupsOf(value protoreflect.EnumValueDescriptor) (*codegenv1.PodStatusGroups, error) {
	groups, ok := proto.GetExtension(value.Options(), codegenv1.E_PodStatusGroups).(*codegenv1.PodStatusGroups)
	if !ok || groups == nil {
		return nil, fmt.Errorf("enum value %s is missing (amesh.codegen.v1.pod_status_groups)", value.Name())
	}
	return groups, nil
}

func filter(statuses []status, member func(*codegenv1.PodStatusGroups) bool) []status {
	var out []status
	for _, s := range statuses {
		if member(s.groups) {
			out = append(out, s)
		}
	}
	return out
}

// groupSpec drives the per-language renderers so a new group only needs a proto
// field plus one entry here.
type groupSpec struct {
	// name is the group's identifier in snake_case; renderers case it per language.
	name   string
	member func(*codegenv1.PodStatusGroups) bool
}

func groupSpecs() []groupSpec {
	return []groupSpec{
		{"active", func(g *codegenv1.PodStatusGroups) bool { return g.GetActive() }},
		{"terminal", func(g *codegenv1.PodStatusGroups) bool { return g.GetTerminal() }},
		{"finished", func(g *codegenv1.PodStatusGroups) bool { return g.GetFinished() }},
		{"relay_connectable", func(g *codegenv1.PodStatusGroups) bool { return g.GetRelayConnectable() }},
		{"resumable_source", func(g *codegenv1.PodStatusGroups) bool { return g.GetResumableSource() }},
	}
}

func camel(snake string) string {
	parts := strings.Split(snake, "_")
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

const header = "Code generated by tools/pod-status-codegen from proto/pod/v1/pod_status.proto. DO NOT EDIT."
