// Code generated by tools/pod-status-codegen from proto/pod/v1/pod_status.proto. DO NOT EDIT.

export type PodStatus =
  | "queued"
  | "initializing"
  | "running"
  | "paused"
  | "disconnected"
  | "completed"
  | "terminated"
  | "orphaned"
  | "error";

export const POD_STATUSES: readonly PodStatus[] = ["queued", "initializing", "running", "paused", "disconnected", "completed", "terminated", "orphaned", "error"];

export const ACTIVE_POD_STATUSES: readonly PodStatus[] = ["queued", "initializing", "running", "paused", "disconnected"];

export const TERMINAL_POD_STATUSES: readonly PodStatus[] = ["terminated", "orphaned", "error"];

export const FINISHED_POD_STATUSES: readonly PodStatus[] = ["completed", "terminated", "orphaned", "error"];

export const RELAY_CONNECTABLE_POD_STATUSES: readonly PodStatus[] = ["running", "paused", "disconnected"];

export const RESUMABLE_SOURCE_POD_STATUSES: readonly PodStatus[] = ["completed", "terminated", "orphaned"];

const activeStatuses: ReadonlySet<string> = new Set(ACTIVE_POD_STATUSES);
export function isPodActive(status: string | null | undefined): boolean {
  return !!status && activeStatuses.has(status);
}

const terminalStatuses: ReadonlySet<string> = new Set(TERMINAL_POD_STATUSES);
export function isPodTerminal(status: string | null | undefined): boolean {
  return !!status && terminalStatuses.has(status);
}

const finishedStatuses: ReadonlySet<string> = new Set(FINISHED_POD_STATUSES);
export function isPodFinished(status: string | null | undefined): boolean {
  return !!status && finishedStatuses.has(status);
}

const relayConnectableStatuses: ReadonlySet<string> = new Set(RELAY_CONNECTABLE_POD_STATUSES);
export function isPodRelayConnectable(status: string | null | undefined): boolean {
  return !!status && relayConnectableStatuses.has(status);
}

const resumableSourceStatuses: ReadonlySet<string> = new Set(RESUMABLE_SOURCE_POD_STATUSES);
export function isPodResumableSource(status: string | null | undefined): boolean {
  return !!status && resumableSourceStatuses.has(status);
}
