package operatorcatalog

func Experts() []ExpertDefinition {
	// Education partners first so oilan bootstrap can persist them even when
	// later video/pattern experts still lack org-specific model/credential IDs.
	return []ExpertDefinition{
		{
			Slug: "official-vehicle-booking-partner", Name: "公务用车助手",
			Summary:     "按校园用车规则收集行程、完成确认与承诺，并在有凭证时提交门户任务。",
			Description: "引导申请人完成规则同意、字段收集、摘要确认、规则校验和用车承诺，缺提交适配器时停在待凭证状态。",
			Category:    "education", Icon: "car",
			Tags:     []string{"education", "campus", "operations", "booking"},
			Outcomes: []string{"申请摘要", "规则检查", "承诺记录", "提交任务", "质检报告"},
			SkillSlugs: []string{
				"official-vehicle-booking",
			},
			Prompt:         "Run one official vehicle booking as a durable workspace. Enforce HITL gates in order, keep portal credentials out of the log, and never claim a campus submit without task-id poll readback.",
			WorkerTypeSlug: "do-agent", RuntimeImageID: 5,
			InteractionMode:    "acp",
			ModelResourceID:    0,
			ConfigOverrides:    map[string]any{},
			ConfigDocumentRefs: map[string]string{"settings": "do-agent-settings"},
			LaunchEnv: []LaunchEnvDeclaration{
				{Name: "VEHICLE_BOOKING_SUBMIT_URL"},
				{Name: "VEHICLE_BOOKING_API_KEY", Secret: true},
				{Name: "CAMPUS_PORTAL_USERNAME", Secret: true},
				{Name: "CAMPUS_PORTAL_PASSWORD", Secret: true},
			},
		},
		{
			Slug: "campus-daily-brief-partner", Name: "校园日报伙伴",
			Summary:     "把校园新闻与通知做成工作日双主持人短播，并在有凭证时合成音频。",
			Description: "按收听日计算新闻窗口、包装开场白与稿件、写出可朗读脚本；缺 TTS 或新闻源时交付脚本并标记待凭证。",
			Category:    "education", Icon: "newspaper",
			Tags:     []string{"education", "campus", "news", "podcast"},
			Outcomes: []string{"新闻窗口", "稿件原文", "播客脚本", "音频成片", "质检报告"},
			SkillSlugs: []string{
				"campus-daily-brief",
			},
			Prompt:         "Produce one weekday campus daily brief. Preserve the packaged opening, cover every article, keep adapter secrets out of the workspace, and do not claim audio or fetch success without the matching artifact.",
			WorkerTypeSlug: "do-agent", RuntimeImageID: 5,
			InteractionMode:    "acp",
			ModelResourceID:    0,
			ConfigOverrides:    map[string]any{},
			ConfigDocumentRefs: map[string]string{"settings": "do-agent-settings"},
			LaunchEnv: []LaunchEnvDeclaration{
				{Name: "CAMPUS_NEWS_SOURCE_URL"},
				{Name: "CAMPUS_NEWS_API_KEY", Secret: true},
				{Name: "CAMPUS_TTS_API_KEY", Secret: true},
				{Name: "CAMPUS_AUDIO_STORE_URL"},
			},
		},
		{
			Slug: "learning-companion-partner", Name: "AI 学伴",
			Summary:     "为单个学生持续维护知识图谱、掌握度和练习复盘的学习伙伴。",
			Description: "沉淀学习资料、构建分层知识图谱、推荐学习路径、生成与批改练习，并留存成长证据。",
			Category:    "education", Icon: "graduation-cap",
			Tags:     []string{"education", "learning", "student", "knowledge-graph"},
			Outcomes: []string{"知识图谱", "掌握度画像", "学习路径", "练习会话", "批改结果", "成长证据"},
			SkillSlugs: []string{
				"learning-companion",
			},
			Prompt:         "Maintain one student's durable learning workspace. Write evidence before conclusions, keep every knowledge-point id stable across files, keep mastery conservative until practice proves it, and never report success without reading the written pages back.",
			WorkerTypeSlug: "do-agent", RuntimeImageID: 5,
			InteractionMode:    "acp",
			ModelResourceID:    0,
			ConfigOverrides:    map[string]any{},
			ConfigDocumentRefs: map[string]string{"settings": "do-agent-settings"},
		},
		{
			Slug: "teacher-assistant-partner", Name: "AI 教师助理",
			Summary:     "面向教师的课程建设、实验建设与教学运营助理。",
			Description: "完成课程设计、课件与实验产出、练习题库、班级与学生账号运营，并留存交付与质检记录。",
			Category:    "education", Icon: "graduation-cap",
			Tags:     []string{"education", "teaching", "course", "operations"},
			Outcomes: []string{"课程方案", "课件正文", "实验手册", "练习题库", "运营记录", "质检报告"},
			SkillSlugs: []string{
				"teacher-assistant", "course-researcher", "course-architect",
				"course-builder", "course-lab-builder",
				"course-practice-builder", "course-ppt",
			},
			Prompt:         "Run teacher-owned course and teaching operations from an explicit plan. Route specialized production to the matching skill, act only within the teacher's permission boundary, keep credentials out of the workspace log, and verify every platform write by reading the resource back.",
			WorkerTypeSlug: "do-agent", RuntimeImageID: 5,
			InteractionMode:    "acp",
			ModelResourceID:    0,
			ConfigOverrides:    map[string]any{},
			ConfigDocumentRefs: map[string]string{"settings": "do-agent-settings"},
			// The platform key is scoped to one teacher, so it is supplied per
			// run by the caller instead of being pinned into the shared spec.
			LaunchEnv: []LaunchEnvDeclaration{
				{Name: "ZHIYONG_PLATFORM_API_KEY", Secret: true},
				{Name: "ZHIYONG_COURSE_API_BASE_URL"},
			},
		},
		{
			Slug: "coding-lab-experiment", Name: "编码实验环境",
			Summary:     "面向 Zhiyong 课程实验的隔离 Agent 编码环境。",
			Description: "按学生实验实例拉起独立 workspace，协助完成编码任务并沉淀可验收产出。",
			Category:    "education", Icon: "terminal",
			Tags:     []string{"education", "lab", "coding", "experiment"},
			Outcomes: []string{"实验产出", "执行记录", "验收摘要"},
			SkillSlugs: []string{
				"coding-lab-experiment",
			},
			Prompt:         "Run one student coding lab in an isolated workspace. Confirm the objective, make incremental verified changes, write evidence under output/ and notes/, and never claim completion without reading the written files back.",
			WorkerTypeSlug: "do-agent", RuntimeImageID: 5,
			InteractionMode:    "acp",
			ModelResourceID:    0,
			ConfigOverrides:    map[string]any{},
			ConfigDocumentRefs: map[string]string{"settings": "do-agent-settings"},
		},
		{
			Slug: "course-development-partner", Name: "课程研发伙伴",
			Summary:     "从教学目标到课程资产的一体化研发伙伴。",
			Description: "完成课程研究、大纲、章节任务、课件正文、实验、练习评价和交付审核。",
			Category:    "education", Icon: "graduation-cap",
			Tags:     []string{"course", "education", "curriculum", "assessment"},
			Outcomes: []string{"课程蓝图", "章节任务", "课件正文", "实验手册", "练习评价", "交付清单"},
			SkillSlugs: []string{
				"course-researcher", "course-architect",
				"course-builder", "course-lab-builder",
				"course-practice-builder", "course-ppt",
			},
			Prompt:         "Develop complete course assets from explicit learning outcomes. Use backward design, keep references mapped to lessons, require human review gates, and verify every deliverable against observable student work.",
			WorkerTypeSlug: "codex-cli", RuntimeImageID: 1,
		},
		{
			Slug: "video-production-expert", Name: "视频制作伙伴",
			Summary:     "从创意到可交付成片的一体化视频制作。",
			Description: "负责短视频方案、素材、Remotion 合成、动效和交付质检。",
			Category:    "video", Icon: "clapperboard",
			Tags:     []string{"video", "production", "remotion", "short-video"},
			Outcomes: []string{"成片方案", "可复现工程", "平台规格成片", "质检报告"},
			SkillSlugs: []string{
				"short-video-directing", "media-rights-research",
				"remotion-video-production", "video-motion-graphics",
				"video-delivery-qa",
			},
			Prompt:          "Own the video from brief to verified master. Confirm creative direction before rendering, preserve asset rights evidence, and do not deliver an unverified file.",
			ModelResourceID: 51,
		},
		{
			Slug: "video-editing-expert", Name: "视频剪辑伙伴",
			Summary:     "以叙事、节奏、声音和字幕为核心完成专业剪辑。",
			Description: "分析素材，确认剪辑策略，生成 EDL，完成动效、字幕、声音和交付检查。",
			Category:    "video", Icon: "scissors",
			Tags:     []string{"video", "editing", "ffmpeg", "subtitles"},
			Outcomes: []string{"剪辑策略", "EDL", "预览片", "交付母版", "质检报告"},
			SkillSlugs: []string{
				"video-editing-workflow", "video-motion-graphics",
				"video-delivery-qa",
			},
			Prompt:          "Edit from an explicit strategy and reversible EDL. Preserve source media, keep subtitles on the output timeline, and verify every cut before delivery.",
			ModelResourceID: 51,
		},
		{
			Slug: "short-video-director", Name: "短视频编导伙伴",
			Summary:     "把传播目标转成可拍、可剪、可验证的短视频执行方案。",
			Description: "完成选题提炼、结构、脚本、分镜、镜头表、素材计划和剪辑简报。",
			Category:    "video", Icon: "film",
			Tags:     []string{"video", "directing", "script", "storyboard"},
			Outcomes: []string{"创意简报", "成稿脚本", "镜头表", "连续性说明", "剪辑简报"},
			SkillSlugs: []string{
				"short-video-directing", "media-rights-research",
				"video-delivery-qa",
			},
			Prompt:          "Turn the objective into a feasible short-video plan. Ground claims in supplied facts, identify every visual source, and hand production an executable script and shot list.",
			ModelResourceID: 51,
		},
		{
			Slug: "pattern-design-partner", Name: "花型设计伙伴",
			Summary:     "把参考图、元素和风格要求转成可评审、可接版的花型方案。",
			Description: "完成花型分析、元素重绘、画布铺排、无缝接版检查和交付建议。",
			Category:    "design", Icon: "palette",
			Tags:     []string{"pattern", "textile", "design", "seamless"},
			Outcomes: []string{"花型分析", "元素生成", "重复画布", "接版证据", "生产风险"},
			SkillSlugs: []string{
				"pattern-generate", "canvas-compose",
				"pattern-seam-review", "lovart-api",
			},
			Prompt:         "Turn visual references into production-aware textile patterns. Keep every source traceable, separate motifs from repeats, prove seam quality, and call out manufacturing risks before delivery.",
			WorkerTypeSlug: "codex-cli", RuntimeImageID: 1,
			SecretRefs: map[string]string{
				"LOVART_ACCESS_KEY": "lovart",
				"LOVART_SECRET_KEY": "lovart",
			},
		},
	}
}
